### ISSUE TITLE
Flicker dataset error

### ISSUE THREAD

**Issue by ajengwulandari** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#1]
Flicker8k dataset error:
Traceback (most recent call last):
  File "create_input_files.py", line 22, in <module>
    max_len=50)
  File "/home/ajeng/Tutorial/image captioning/code/attention/a-PyTorch-Tutorial-to-Image-Captioning/utils.py", line 115, in create_input_files
    img = imread(impaths[i])
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ajeng/Tutorial/image captioning/code/attention/a-PyTorch-Tutorial-to-Image-Captioning/caption data/flickr8k/Flicker8k_Dataset/2513260012_03d33305cf.jpg'

Flicker30k dataset error:
Traceback (most recent call last):
  File "create_input_files.py", line 32, in <module>
    max_len=50)
  File "/home/ajeng/Tutorial/image captioning/code/attention/a-PyTorch-Tutorial-to-Image-Captioning/utils.py", line 115, in create_input_files
    img = imread(impaths[i])
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/ajeng/anaconda3/envs/pytorch/lib/python3.6/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ajeng/Tutorial/image captioning/code/attention/a-PyTorch-Tutorial-to-Image-Captioning/caption data/flickr30k/flickr30k_images/1000092795.jpg'

I don't understand why I get this error when i tried it in flicker dataset. Can you help me? Thanks

**Comment by sgrvinod** [comment]
Those are the first files in the Flickr8k and Flickr30k datasets, so I'm guessing the folder path (`image_folder`) is not correct. Can you verify? One source of the error might be that Flickr is sometimes spelled with an 'e', like Flicker. (It's even spelled this way in the official download of the Flickr8k dataset, as you might have noticed).

I just downloaded it and tried it. It works for me. My function is written as 

```python
create_input_files(dataset='flickr8k',
                   karpathy_json_path='../caption data/dataset_flickr8k.json',
                   image_folder='../caption data/Flicker8k_Dataset/',
                   ...)
```

**Comment by ajengwulandari** [comment]
Thank you very much. Sorry for the inconvenience

**Comment by prraoo** [comment]
@sgrvinod how can one get dataset_flickr30k.json or dataset_flickr8k.json files?

**Comment by rongtongxueya** [comment]
I want to know why the path to the image_folder and output_folder are the same folder? Do I need to have flickr8k images in this folder or do I just need to create an empty folder
