### ISSUE TITLE
Cannot load pretrained model..!

### ISSUE THREAD

**Issue by mandal4** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#113]
Hi there. 
I have tried to run caption.py to inference with pretrained model (BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth).
But i got following error. I didn't change anything in models.Encoder.
Is there anyone help me?

`/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'models.Encoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/home/geonuk/workhard/showAT/caption.py", line 201, in <module>
    checkpoint = torch.load(args.model, map_location=str(device))
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 320, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/home/geonuk/anaconda3/envs/py36torch04/lib/python3.6/site-packages/torch/serialization.py", line 69, in _cuda_deserialize
    device = max(int(location[5:]), 0)
ValueError: invalid literal for int() with base 10: ''`

**Comment by mandal4** [comment]
I fixed it by changing `    checkpoint = torch.load(args.model, map_location=str(device))` in caption.py 
to
`    checkpoint = torch.load(args.mode)`

**Comment by adib0073** [comment]
@mandal4  - Hey I am getting the same issue. I see that the file that you have used is of format .pth instead of .pth.tar.
How are you untarring it?
