### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by Shanks0465** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#115]
Traceback (most recent call last):
  File "train.py", line 329, in <module>
    main()
  File "train.py", line 116, in main
    epoch=epoch)
  File "train.py", line 161, in train
    for i, (imgs, caps, caplens) in enumerate(train_loader):
ValueError: too many values to unpack (expected 3)

Using Pytorch 1.2.0

**Comment by kmario23** [comment]
This has already been addressed. Please see #86

**Comment by NearStart** [comment]
> Traceback (most recent call last):
> File "train.py", line 329, in 
> main()
> File "train.py", line 116, in main
> epoch=epoch)
> File "train.py", line 161, in train
> for i, (imgs, caps, caplens) in enumerate(train_loader):
> ValueError: too many values to unpack (expected 3)
> 
> Using Pytorch 1.2.0

Hey, I also met this problem. Have you found the solution?
