### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ShivanshuPurohit** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#123]
While running train.py I encountered this error

`Traceback (most recent call last):`
  `File "train.py", line 329, in <module>`
    `main()`
  `File "train.py", line 116, in main
    epoch=epoch)`
  `File "train.py", line 178, in train`
    `scores, _ = pack_padded_sequence(scores, decode_lengths, batch_first=True)`
`ValueError: too many values to unpack (expected 2)`

Even though ` scores, _ = pack_padded_sequence(scores, decode_lengths, batch_first=True)` asks for 2 values.

**Comment by ShivanshuPurohit** [comment]
Edit: I found that `scores, *_ = pack_padded_sequence(scores, decode_lengths, batch_first=True)` solved the issue
