### ISSUE TITLE
caption.py:IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by AndreSun98** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#175]
When I run caption.py,I got the following error: 
Traceback (most recent call last):
  File "D:/2021/sjt/code/a-PyTorch-Tutorial-to-Image-Captioning-master/caption.py", line 217, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "D:/2021/sjt/code/a-PyTorch-Tutorial-to-Image-Captioning-master/caption.py", line 113, in caption_image_beam_search
    seqs_alpha = torch.cat([seqs_alpha[prev_word_inds.long()], alpha[prev_word_inds].unsqueeze(1)],
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by zhongchaotie** [comment]
I had the same problem

**Comment by vernal0** [comment]
I have the same problem. Have you solved it？

**Comment by HackInSouth** [comment]
prev_word_inds = top_k_words / vocab_size
You can try changing the "/" in the above code to "//".

**Comment by wenshihao1** [comment]
你好，解决了没

**Comment by 01620syf** [comment]
我也遇到了同样的问题，请问怎么解决
