### ISSUE TITLE
Failed to create .hdf5 files 

### ISSUE THREAD

**Issue by supriamir** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#183]
Hi @sgrvinod 

I got this error when i run the create_input_files.py

Traceback (most recent call last):
File "D:\PyTorch-Tutorial-to-Image-Captioning-master\create_input_files.py", line 5, in
create_input_files(dataset='coco',
File "D:\PyTorch-Tutorial-to-Image-Captioning-master\utils.py", line 158, in create_input_files
json.dump(caplens, j)
File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "C:\Users\HORIO-LAB\AppData\Roaming\Python\Python39\site-packages\h5py_hl\files.py", line 544, in exit
self.close()
File "C:\Users\HORIO-LAB\AppData\Roaming\Python\Python39\site-packages\h5py_hl\files.py", line 526, in close
self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py\h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to extend file properly)

**Comment by lollinng** [comment]
Do check this out  - https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/7#issuecomment-410666483
