### ISSUE TITLE
Please help me with the error:RuntimeError: Expected target size [32, 9490], got [32, 51]

### ISSUE THREAD

**Issue by 2068439567** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#195]
Traceback (most recent call last):
  File "D:\majority_design\image_caption\ic_train.py", line 322, in <module>
    main()
  File "D:\majority_design\image_caption\ic_train.py", line 116, in main
    train(train_loader=train_loader,
  File "D:\majority_design\image_caption\ic_train.py", line 180, in train
    loss = criterion(scores, targets)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 1164, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected target size [32, 9490], got [32, 51]

When i debug the code, i found scores's size is (32, 16, 9490), but targets's size is (32, 51)

i am just a rookie of DL, please help me!!! Thank you very much!!!

**Comment by Le-up** [comment]
I also encountered the same problem. Have you solved it？
