### ISSUE TITLE
RuntimeError Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'other' 

### ISSUE THREAD

**Issue by JohnComeon** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#51]
Hello, When I run the following command: python caption.py --img='path/to/image.jpeg' --model='path/to/BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar' --word_map='path/to/WORDMAP_coco_5_cap_per_img_5_min_word_freq.json' --beam_size=5 , I get the errors.Could you give me some suggestioins on how to fix it?

**Comment by sgrvinod** [comment]
Hi @JohnComeon, this is happening because it expects a tensor on the GPU but is receiving a tensor on the CPU. You might be having the same problem as in #46. Can you check if that fixes it?

Also, paste the full error message with the traceback. Thanks!

**Comment by JohnComeon** [comment]
Traceback (most recent call last):
  File "caption.py", line 215, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 43, in caption_image_beam_search
    image = transform(img)  # (3, 256, 256)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'other'

It seems that I have the same problem as in #46 .
But, when I used the method you proposed in #46 ,  new problems arouse.
The error is as follows:

Traceback (most recent call last):
  File "caption.py", line 215, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 48, in caption_image_beam_search
    encoder_out = encoder(image)  # (1, enc_image_size, enc_image_size, encoder_dim)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cw2018/a-PyTorch-Tutorial-to-Image-Captioning-master/main/models.py", line 35, in forward
    out = self.resnet(images)  # (batch_size, 2048, image_size/32, image_size/32)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

**Comment by JohnComeon** [comment]
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
Traceback (most recent call last):
  File "caption.py", line 215, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 43, in caption_image_beam_search
    image = transform(img)  # (3, 256, 256)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #4 'other'

It seems that I have the same problem as in #46 .
But when I used the method you proposed in #46 ,another problem arouse.
The error is as follows

 Traceback (most recent call last):
  File "caption.py", line 215, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 48, in caption_image_beam_search
    encoder_out = encoder(image)  # (1, enc_image_size, enc_image_size, encoder_dim)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cw2018/a-PyTorch-Tutorial-to-Image-Captioning-master/main/models.py", line 35, in forward
    out = self.resnet(images)  # (batch_size, 2048, image_size/32, image_size/32)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

**Comment by sgrvinod** [comment]
It seems the new problem is that the encoder is on the CPU and therefore expects a tensor on the CPU, but the image tensor is on the GPU.

```python
    img = torch.FloatTensor(img)
    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])
    transform = transforms.Compose([normalize])
    image = transform(img).to(device)  # (3, 256, 256)

    # Encode
    image = image.unsqueeze(0)  # (1, 3, 256, 256)
    print(device)
    print(image.is_cuda)
    print(next(encoder.parameters()).is_cuda)
    encoder_out = encoder(image)  # (1, enc_image_size, enc_image_size, encoder_dim)
```

Can you try this code with the print statements to see what devices they're on?

**Comment by JohnComeon** [comment]
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expecte                   d 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expecte                   d 96, got 88
  return f(*args, **kwds)
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from                    `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from                    `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
cuda
True
True
Traceback (most recent call last):
  File "caption.py", line 221, in <module>
    visualize_att(args.img, seq, alphas, rev_word_map, args.smooth)
  File "caption.py", line 173, in visualize_att
    plt.subplot(np.ceil(len(words) / 5.), 5, t + 1)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 1043, in subplot
    fig = gcf()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by sgrvinod** [comment]
```
cuda
True
True
```
This is correct. It means that you have a CUDA device, and that both the encoder and the input image are on it.

About your new error, it seems to be something to do with `matplotlib`. Try the fix mentioned [here](https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable/43592515).

**Comment by dobahuy6789** [comment]
Traceback (most recent call last):
  File "caption.py", line 228, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, args.img, word_map, args.beam_size)
  File "caption.py", line 54, in caption_image_beam_search
    image = transform(img).to(device)  # (3, 256, 256)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 94, in __call__
    img = t(img)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 269, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 360, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_tensor.py", line 959, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
Could you give me some suggestioins on how to fix it?
