### ISSUE TITLE
Evaluation issue

### ISSUE THREAD

**Issue by anand-kummari** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#63]
Hi, 
I am new to pytorch. I have trained as you mentioned using flickr8k dataset. After training how to run eval.py? I do not have any checkpoint outputed from the code. How did you get checkpoint? I am running the code in google colab. on running the eval.py i am getting the following error

Traceback (most recent call last):
  File "/content/gdrive/My Drive/B.Tech Project/Attention/eval.py", line 179, in <module>
    print("\nBLEU-4 score @ beam size of %d is %.4f." % (beam_size, evaluate(beam_size)))
  File "/content/gdrive/My Drive/B.Tech Project/Attention/eval.py", line 131, in evaluate
    incomplete_inds = [ind for ind, next_word in enumerate(next_word_inds) if
  File "/content/gdrive/My Drive/B.Tech Project/Attention/eval.py", line 132, in <listcomp>
    next_word != word_map['<end>']]
RuntimeError: CUDA error: device-side assert triggered

**Comment by aliciaviernes** [comment]
Did you manage to solve it? I assume that it has to do with the Wordmap.
