### ISSUE TITLE
AttributeError: 'Meteor' object has no attribute 'lock' 

### ISSUE THREAD

**Issue by Sun-WeiZhen** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#92]
Hi,
This is a very excellent work for me ! Thank you a lot for providing the code in Pytorch.I encountered the following issues during the verification.

Traceback (most recent call last):
File "D:/AIBU/image_caption/showAttendTell/train.py", line 26, in 
main()
File "D:/AIBU/image_caption/showAttendTell/train.py", line 22, in main
solver.train()
File "D:\AIBU\image_caption\showAttendTell\core\solver.py", line 172, in train
scores = evaluate(data_path='./data', split='val', get_scores=True)
File "D:\AIBU\image_caption\showAttendTell\core\bleu.py", line 47, in evaluate
final_scores = score(ref, hypo)
File "D:\AIBU\image_caption\showAttendTell\core\bleu.py", line 14, in score
(Meteor(),"METEOR"),
File "D:\AIBU\image_caption\showAttendTell\pycocoevalcap\meteor\meteor.py", line 24, in init
stderr=subprocess.PIPE)
File "D:\software\Anaconda\lib\subprocess.py", line 709, in init
restore_signals, start_new_session)
File "D:\software\Anaconda\lib\subprocess.py", line 997, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <bound method Meteor.del of <pycocoevalcap.meteor.meteor.Meteor object at 0x000001E3288BC6D8>>
Traceback (most recent call last):
File "D:\AIBU\image_caption\showAttendTell\pycocoevalcap\meteor\meteor.py", line 76, in del
self.lock.acquire()
AttributeError: 'Meteor' object has no attribute 'lock'

How to deal with it? Thank you!

**Comment by yvfengZhong** [comment]
Hello, I have the same problem.
I found that this problem may be related to the fact that Java is not installed on the system.
You can test whether Java is installed in the system through command `java -version`.
If Java is not installed, you can execute command `sudo apt update
sudo apt install openjdk-11-jdk`.
I hope it works for you!

**Comment by yvfengZhong** [comment]
Hello, I have the same problem.
I found that this problem may be related to the fact that Java is not installed on the system.
You can test whether Java is installed in the system through command `java -version`.
If Java is not installed, you can execute command `sudo apt update
sudo apt install openjdk-11-jdk`.
I hope it works for you!
